name: Build Addons
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Build Addons
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r _build/requirements.txt
          cd _build
          python -m build

      - name: Create Release Tag
        id: release_tag
        run: |
          echo "{tag}={release_$(date +"%Y_%m_%d_%H_%M_%S")}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{steps.release_tag.outputs.tag}}
          files: addons.zip
          generate_release_notes: true
          make_latest: true
